MASTER_PWD_HASH = "YOUR MASTER PWD HASH GOES HERE"
DB_NAME = "YOUR POSTGRESQL DB NAME GOES HERE"
DB_UNAME = "YOUR POSTGRESQL USERNAME GOES HERE"  # "postgres" by default
DB_PWD = "YOUR POSTGRESQL DB PASSWORD GOES HERE"
DB_TABLE_NAME = 'YOUR DB TABLE NAME GOES HERE'  # Ex: 'public."Table"'
SALT = b""  # Feel free to put any binary string here Ex: b".Y\x20\xBF\x045\xAC"
